#!/usr/bin/env php
<?php
use CodeIgniter\Boot;
use Config\Paths;

if (str_starts_with(PHP_SAPI, 'cgi')) exit("CodeIgniter CLI requires php-cli.\n");
if (version_compare(PHP_VERSION, '8.2', '<')) exit("PHP 8.2 or higher is required. Current: ".PHP_VERSION."\n");
error_reporting(E_ALL);
ini_set('display_errors','1');
define('FCPATH', __DIR__.DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR);
chdir(FCPATH);
require FCPATH.'../app/Config/Paths.php';
$paths=new Paths();
require $paths->systemDirectory.'/Boot.php';
exit(Boot::bootSpark($paths));