-- Perfect LPG POS / ERP - Complete install schema
-- MySQL 8.0+ / InnoDB / utf8mb4. Run this file once on a fresh server.
CREATE DATABASE IF NOT EXISTS perfect_lpg CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE perfect_lpg;
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS audit_logs,inventory_wastage_logs,inventory_policies,cash_transactions,cash_sessions,cash_registers,expenses,expense_categories,inventory_movements,cylinder_units,inventory_opening_balances,customer_receipts,supplier_payments,purchase_payments,purchase_items,purchases,sale_payments,sale_items,sales,rate_change_log,rate_cards,customers,suppliers,role_permissions,permissions,users,roles,locations,cylinder_types;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE locations(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL,address VARCHAR(255),city VARCHAR(80),phone VARCHAR(30),is_active BOOLEAN NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)ENGINE=InnoDB;
CREATE TABLE shop_settings(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL UNIQUE,default_sale_mode ENUM('sell_gas_only','replace_same','sell_filled','replace_different','sell_empty') NOT NULL DEFAULT 'sell_gas_only',default_transaction_type ENUM('gas_sale','cylinder_sale','security_deposit','cylinder_return') NOT NULL DEFAULT 'gas_sale',default_gas_entry_mode ENUM('quantity','amount','cylinders') NOT NULL DEFAULT 'quantity',pos_visible_transaction_types TEXT NULL,individual_cylinder_tracking BOOLEAN NOT NULL DEFAULT 0,allow_pos_source_cylinder_selection BOOLEAN NOT NULL DEFAULT 0,include_security_deposit_in_os BOOLEAN NOT NULL DEFAULT 0,deposit_payment_allocation_rule ENUM('gas_first','deposit_first','manual') NOT NULL DEFAULT 'deposit_first',allow_return_gas_qty BOOLEAN NOT NULL DEFAULT 0,return_gas_affects_os BOOLEAN NOT NULL DEFAULT 0,allow_empty_issued_return_gas BOOLEAN NOT NULL DEFAULT 0,allow_return_gas_over_issued BOOLEAN NOT NULL DEFAULT 0,default_payment_mode ENUM('cash','cheque','online','credit') NOT NULL DEFAULT 'cash',purchase_void_enabled BOOLEAN NOT NULL DEFAULT 0,pos_font_size_px DECIMAL(4,1) NOT NULL DEFAULT 14.0,theme_mode ENUM('light','dark') NOT NULL DEFAULT 'light',font_family VARCHAR(30) NOT NULL DEFAULT 'system',primary_color CHAR(7) NOT NULL DEFAULT '#1b2a3a',accent_color CHAR(7) NOT NULL DEFAULT '#ff7a1a',stock_validation_enabled BOOLEAN NOT NULL DEFAULT 1,allow_stock_override BOOLEAN NOT NULL DEFAULT 1,credit_limit_validation_mode ENUM('none','customer','shop') NOT NULL DEFAULT 'none',shop_credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,backup_enabled BOOLEAN NOT NULL DEFAULT 0,db_backup_url VARCHAR(500),backup_notes TEXT,smtp_host VARCHAR(255),smtp_port INT NOT NULL DEFAULT 587,smtp_username VARCHAR(255),smtp_password TEXT,smtp_encryption VARCHAR(10) NOT NULL DEFAULT 'tls',smtp_from_email VARCHAR(255),smtp_from_name VARCHAR(150) DEFAULT 'Perfect LPG',smtp_enabled BOOLEAN NOT NULL DEFAULT 0,receipt_title VARCHAR(120) NOT NULL DEFAULT 'SALE RECEIPT',receipt_footer VARCHAR(500) NOT NULL DEFAULT 'Thank you',show_address_on_receipt BOOLEAN NOT NULL DEFAULT 1,settings_note VARCHAR(500),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE roles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(40) NOT NULL UNIQUE,name VARCHAR(80) NOT NULL,description VARCHAR(255))ENGINE=InnoDB;
CREATE TABLE permissions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(80) NOT NULL UNIQUE,name VARCHAR(120) NOT NULL)ENGINE=InnoDB;
CREATE TABLE role_permissions(role_id BIGINT UNSIGNED NOT NULL,permission_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(role_id,permission_id),FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE,FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE users(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED,role_id BIGINT UNSIGNED NOT NULL,full_name VARCHAR(120) NOT NULL,username VARCHAR(60) NOT NULL UNIQUE,email VARCHAR(150) UNIQUE,password_hash VARCHAR(255) NOT NULL,is_active BOOLEAN NOT NULL DEFAULT 1,last_login_at DATETIME,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE SET NULL,FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE RESTRICT,KEY idx_users_role(role_id))ENGINE=InnoDB;
CREATE TABLE cylinder_types(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) NOT NULL UNIQUE,name VARCHAR(60) NOT NULL,capacity_kg DECIMAL(8,3) NOT NULL UNIQUE,tare_weight_kg DECIMAL(8,3),empty_cylinder_price DECIMAL(14,4) NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT 1,sort_order SMALLINT UNSIGNED NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CHECK(capacity_kg>0))ENGINE=InnoDB;
CREATE TABLE customers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) UNIQUE,name VARCHAR(150) NOT NULL,phone VARCHAR(30),city VARCHAR(80),address VARCHAR(255),vehicle_no VARCHAR(40),credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,allow_credit_sale BOOLEAN NOT NULL DEFAULT 0,opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_customer_name(name),CHECK(credit_limit>=0))ENGINE=InnoDB;
CREATE TABLE suppliers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) UNIQUE,name VARCHAR(150) NOT NULL,phone VARCHAR(30),city VARCHAR(80),address VARCHAR(255),credit_limit DECIMAL(14,2) NOT NULL DEFAULT 0,opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,KEY idx_supplier_name(name),CHECK(credit_limit>=0))ENGINE=InnoDB;
CREATE TABLE rate_cards(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED,rate_type ENUM('gas_per_kg','cylinder_package') NOT NULL,cylinder_type_id BIGINT UNSIGNED NULL,rate_value DECIMAL(14,4) NOT NULL,effective_from DATETIME NOT NULL,effective_to DATETIME,created_by BIGINT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE SET NULL,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_rate_lookup(location_id,rate_type,cylinder_type_id,effective_from),CHECK(rate_value>=0),CHECK((rate_type='gas_per_kg' AND cylinder_type_id IS NULL) OR(rate_type='cylinder_package' AND cylinder_type_id IS NOT NULL)))ENGINE=InnoDB;
CREATE TABLE rate_change_log(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,rate_card_id BIGINT UNSIGNED,location_id BIGINT UNSIGNED,rate_type ENUM('gas_per_kg','cylinder_package') NOT NULL,cylinder_type_id BIGINT UNSIGNED,old_rate DECIMAL(14,4),new_rate DECIMAL(14,4) NOT NULL,changed_by BIGINT UNSIGNED,changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,reason VARCHAR(255),FOREIGN KEY(rate_card_id) REFERENCES rate_cards(id) ON DELETE SET NULL,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE SET NULL,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE SET NULL,FOREIGN KEY(changed_by) REFERENCES users(id) ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE sales(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sale_no VARCHAR(40) NOT NULL,location_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED,transaction_type ENUM('filled_cylinder','refill_service','cylinder_exchange','empty_intake','empty_sale','mixed','gas_sale','cylinder_sale','security_deposit','cylinder_return') NOT NULL,status ENUM('posted','voided') NOT NULL DEFAULT 'posted',transaction_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,total_kg DECIMAL(14,3) NOT NULL DEFAULT 0,subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,security_deposit_amount DECIMAL(14,2) NOT NULL DEFAULT 0,security_deposit_refund_amount DECIMAL(14,2) NOT NULL DEFAULT 0,credit_amount DECIMAL(14,2) NOT NULL DEFAULT 0,previous_os_balance DECIMAL(14,2) NOT NULL DEFAULT 0,receipt_amount DECIMAL(14,2) NOT NULL DEFAULT 0,net_receivable_amount DECIMAL(14,2) NOT NULL DEFAULT 0,os_balance DECIMAL(14,2) NOT NULL DEFAULT 0,return_gas_ledger_amount DECIMAL(14,2) NOT NULL DEFAULT 0,custom_rate_flag BOOLEAN NOT NULL DEFAULT 0,notes VARCHAR(500),created_by BIGINT UNSIGNED,voided_by BIGINT UNSIGNED,voided_at DATETIME,void_reason VARCHAR(255),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_sale_no(location_id,sale_no),KEY idx_sale_date(transaction_at),KEY idx_sale_customer(customer_id,transaction_at),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(voided_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(subtotal>=0 AND discount_amount>=0 AND total_amount>=0 AND credit_amount>=0))ENGINE=InnoDB;
CREATE TABLE sale_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sale_id BIGINT UNSIGNED NOT NULL,line_no SMALLINT UNSIGNED NOT NULL,line_type ENUM('filled_cylinder','refill_kg','empty_cylinder') NOT NULL,cylinder_type_id BIGINT UNSIGNED,customer_cylinder_unit_id BIGINT UNSIGNED NULL,quantity DECIMAL(14,3) NOT NULL,gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,applied_rate DECIMAL(14,4) NOT NULL,gas_rate DECIMAL(14,4) NOT NULL DEFAULT 0,cylinder_price DECIMAL(14,4) NOT NULL DEFAULT 0,standard_rate DECIMAL(14,4),custom_rate_flag BOOLEAN NOT NULL DEFAULT 0,empty_cylinder_received DECIMAL(14,3) NOT NULL DEFAULT 0,line_discount DECIMAL(14,2) NOT NULL DEFAULT 0,line_total DECIMAL(14,2) NOT NULL,notes VARCHAR(255),UNIQUE KEY uq_sale_line(sale_id,line_no),FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,CHECK(quantity>0))ENGINE=InnoDB;
CREATE TABLE sale_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,sale_id BIGINT UNSIGNED NOT NULL,payment_type ENUM('sale','security_deposit','security_deposit_refund') NOT NULL DEFAULT 'sale',payment_mode ENUM('cash','cheque','online','credit') NOT NULL,amount DECIMAL(14,2) NOT NULL,reference_no VARCHAR(100),payment_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,received_by BIGINT UNSIGNED,FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE RESTRICT,FOREIGN KEY(received_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_sale_payment(sale_id,payment_mode),CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE purchases(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,purchase_no VARCHAR(40) NOT NULL,location_id BIGINT UNSIGNED NOT NULL,supplier_id BIGINT UNSIGNED NOT NULL,status ENUM('posted','voided') NOT NULL DEFAULT 'posted',transaction_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,subtotal DECIMAL(14,2) NOT NULL DEFAULT 0,discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0,total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,credit_amount DECIMAL(14,2) NOT NULL DEFAULT 0,notes VARCHAR(500),created_by BIGINT UNSIGNED,voided_by BIGINT UNSIGNED,voided_at DATETIME,void_reason VARCHAR(255),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_purchase_no(location_id,purchase_no),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(voided_by) REFERENCES users(id) ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE purchase_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,purchase_id BIGINT UNSIGNED NOT NULL,line_no SMALLINT UNSIGNED NOT NULL,line_type ENUM('gas_kg','filled_cylinder','empty_cylinder') NOT NULL,cylinder_type_id BIGINT UNSIGNED,quantity DECIMAL(14,3) NOT NULL,actual_gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,unit_rate DECIMAL(14,4) NOT NULL,line_total DECIMAL(14,2) NOT NULL,UNIQUE KEY uq_purchase_line(purchase_id,line_no),FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,CHECK(quantity>0))ENGINE=InnoDB;
CREATE TABLE purchase_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,purchase_id BIGINT UNSIGNED NOT NULL,payment_mode ENUM('cash','cheque','online','credit') NOT NULL,amount DECIMAL(14,2) NOT NULL,reference_no VARCHAR(100),payment_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_by BIGINT UNSIGNED,FOREIGN KEY(purchase_id) REFERENCES purchases(id) ON DELETE RESTRICT,FOREIGN KEY(paid_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE customer_receipts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,receipt_no VARCHAR(40) NOT NULL,location_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,status ENUM('posted','voided') NOT NULL DEFAULT 'posted',amount DECIMAL(14,2) NOT NULL,payment_mode ENUM('cash','cheque','online') NOT NULL,receipt_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,reference_no VARCHAR(100),notes VARCHAR(255),created_by BIGINT UNSIGNED,UNIQUE KEY uq_receipt_no(location_id,receipt_no),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE supplier_payments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_no VARCHAR(40) NOT NULL,location_id BIGINT UNSIGNED NOT NULL,supplier_id BIGINT UNSIGNED NOT NULL,status ENUM('posted','voided') NOT NULL DEFAULT 'posted',amount DECIMAL(14,2) NOT NULL,payment_mode ENUM('cash','cheque','online') NOT NULL,payment_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,reference_no VARCHAR(100),notes VARCHAR(255),created_by BIGINT UNSIGNED,UNIQUE KEY uq_supplier_payment_no(location_id,payment_no),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(supplier_id) REFERENCES suppliers(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE shop_purchase_void_users(
id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
location_id BIGINT UNSIGNED NOT NULL,
user_id BIGINT UNSIGNED NOT NULL,
created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
UNIQUE KEY uq_shop_purchase_void_user(location_id,user_id),
FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE,
FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
)ENGINE=InnoDB;
CREATE TABLE inventory_opening_balances(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,inventory_date DATE NOT NULL,inventory_type ENUM('gas_kg','filled_cylinder','empty_cylinder') NOT NULL,cylinder_type_id BIGINT UNSIGNED,quantity DECIMAL(14,3) NOT NULL,comments VARCHAR(500),opening_batch_key VARCHAR(64) NOT NULL DEFAULT '',created_by BIGINT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_inventory_opening_batch(location_id,inventory_date,inventory_type,cylinder_type_id,opening_batch_key),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(quantity>=0))ENGINE=InnoDB;
CREATE TABLE cylinder_units(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,cylinder_type_id BIGINT UNSIGNED NOT NULL,unit_code VARCHAR(60) NOT NULL,status ENUM('filled','empty','custody','sold') NOT NULL DEFAULT 'empty',custody_customer_id BIGINT UNSIGNED NULL,gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,source_type VARCHAR(40),source_id BIGINT UNSIGNED,created_by BIGINT UNSIGNED,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_cylinder_unit_code(location_id,unit_code),KEY idx_cylinder_units_stock(location_id,cylinder_type_id,status),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(gas_weight_kg>=0))ENGINE=InnoDB;
CREATE TABLE inventory_policies(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,cylinder_type_id BIGINT UNSIGNED NULL,stock_validation_enabled BOOLEAN NOT NULL DEFAULT 1,wastage_mode ENUM('percent','fixed_kg') NOT NULL DEFAULT 'percent',wastage_percent DECIMAL(8,3) NOT NULL DEFAULT 0,wastage_fixed_kg DECIMAL(8,3) NOT NULL DEFAULT 0,is_active BOOLEAN NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_inventory_policy(location_id,cylinder_type_id),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(wastage_percent>=0 AND wastage_percent<=100),CHECK(wastage_fixed_kg>=0))ENGINE=InnoDB;
CREATE TABLE inventory_wastage_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,cylinder_type_id BIGINT UNSIGNED NULL,cylinder_unit_id BIGINT UNSIGNED NULL,gas_weight_kg DECIMAL(14,3) NOT NULL,reason VARCHAR(255) NOT NULL,source_type VARCHAR(40) NOT NULL DEFAULT 'adjustment',source_id BIGINT UNSIGNED NOT NULL DEFAULT 0,created_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_unit_id) REFERENCES cylinder_units(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_wastage_date(location_id,created_at),KEY idx_wastage_type(location_id,cylinder_type_id))ENGINE=InnoDB;
CREATE TABLE inventory_movements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,inventory_type ENUM('gas_kg','filled_cylinder','empty_cylinder') NOT NULL,cylinder_type_id BIGINT UNSIGNED,quantity DECIMAL(14,3) NOT NULL,direction ENUM('in','out','adjustment') NOT NULL,movement_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,source_type VARCHAR(40) NOT NULL,source_id BIGINT UNSIGNED NOT NULL,source_line_id BIGINT UNSIGNED,cylinder_unit_id BIGINT UNSIGNED,created_by BIGINT UNSIGNED,notes VARCHAR(255),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_unit_id) REFERENCES cylinder_units(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_inventory(location_id,inventory_type,cylinder_type_id,movement_at),KEY idx_inventory_source(source_type,source_id),CHECK(quantity>0))ENGINE=InnoDB;
ALTER TABLE sale_items ADD KEY idx_sale_item_customer_cylinder(customer_cylinder_unit_id),ADD CONSTRAINT fk_sale_item_customer_cylinder FOREIGN KEY(customer_cylinder_unit_id) REFERENCES cylinder_units(id) ON DELETE RESTRICT;
ALTER TABLE cylinder_units ADD KEY idx_cylinder_custody_customer(location_id,custody_customer_id,status),ADD CONSTRAINT fk_cylinder_custody_customer FOREIGN KEY(custody_customer_id) REFERENCES customers(id) ON DELETE RESTRICT;

CREATE TABLE cylinder_custody(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,cylinder_unit_id BIGINT UNSIGNED NOT NULL,status ENUM('issued','returned') NOT NULL DEFAULT 'issued',issue_sale_id BIGINT UNSIGNED NULL,return_sale_id BIGINT UNSIGNED NULL,deposit_amount DECIMAL(14,2) NOT NULL DEFAULT 0,issued_gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,returned_gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,consumed_gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,issued_gas_rate DECIMAL(14,4) NOT NULL DEFAULT 0,return_gas_rate DECIMAL(14,4) NOT NULL DEFAULT 0,issued_condition ENUM('filled','empty') NOT NULL DEFAULT 'empty',refund_amount DECIMAL(14,2) NOT NULL DEFAULT 0,issued_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,returned_at DATETIME NULL,created_by BIGINT UNSIGNED NULL,updated_by BIGINT UNSIGNED NULL,notes VARCHAR(255) NULL,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT,FOREIGN KEY(cylinder_unit_id) REFERENCES cylinder_units(id) ON DELETE RESTRICT,FOREIGN KEY(issue_sale_id) REFERENCES sales(id) ON DELETE RESTRICT,FOREIGN KEY(return_sale_id) REFERENCES sales(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_custody_unit_status(cylinder_unit_id,status),KEY idx_custody_customer(location_id,customer_id,status),KEY idx_custody_issue_sale(issue_sale_id),KEY idx_custody_return_sale(return_sale_id),CHECK(deposit_amount>=0 AND refund_amount>=0))ENGINE=InnoDB;

CREATE TABLE customer_security_deposits(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,customer_id BIGINT UNSIGNED NOT NULL,entry_type ENUM('hold','refund') NOT NULL,amount DECIMAL(14,2) NOT NULL,sale_id BIGINT UNSIGNED NULL,custody_id BIGINT UNSIGNED NULL,transaction_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,created_by BIGINT UNSIGNED NULL,notes VARCHAR(255) NULL,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(customer_id) REFERENCES customers(id) ON DELETE RESTRICT,FOREIGN KEY(sale_id) REFERENCES sales(id) ON DELETE RESTRICT,FOREIGN KEY(custody_id) REFERENCES cylinder_custody(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_deposit_customer(location_id,customer_id,transaction_at),KEY idx_deposit_sale(sale_id),CHECK(amount>0))ENGINE=InnoDB;

CREATE TABLE cash_registers(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,code VARCHAR(30) NOT NULL,name VARCHAR(80) NOT NULL,is_active BOOLEAN NOT NULL DEFAULT 1,UNIQUE KEY uq_register(location_id,code),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT)ENGINE=InnoDB;
CREATE TABLE cash_sessions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,register_id BIGINT UNSIGNED NOT NULL,opened_by BIGINT UNSIGNED NOT NULL,opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,opening_cash DECIMAL(14,2) NOT NULL DEFAULT 0,closed_by BIGINT UNSIGNED,closed_at DATETIME,counted_cash DECIMAL(14,2),status ENUM('open','closed') NOT NULL DEFAULT 'open',notes VARCHAR(255),FOREIGN KEY(register_id) REFERENCES cash_registers(id) ON DELETE RESTRICT,FOREIGN KEY(opened_by) REFERENCES users(id) ON DELETE RESTRICT,FOREIGN KEY(closed_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(opening_cash>=0))ENGINE=InnoDB;
CREATE TABLE cash_transactions(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,cash_session_id BIGINT UNSIGNED NOT NULL,transaction_type ENUM('opening_float','sale_cash','customer_receipt','purchase_cash','supplier_payment','expense','manual_in','manual_out','cash_handover','security_deposit','security_deposit_refund') NOT NULL,direction ENUM('in','out') NOT NULL,amount DECIMAL(14,2) NOT NULL,transaction_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,reference_type VARCHAR(40),reference_id BIGINT UNSIGNED,created_by BIGINT UNSIGNED,notes VARCHAR(255),FOREIGN KEY(cash_session_id) REFERENCES cash_sessions(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,KEY idx_cash_session(cash_session_id,transaction_at),CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE expense_categories(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(30) NOT NULL UNIQUE,name VARCHAR(80) NOT NULL,is_active BOOLEAN NOT NULL DEFAULT 1)ENGINE=InnoDB;
CREATE TABLE expenses(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,expense_no VARCHAR(40) NOT NULL,location_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED NOT NULL,amount DECIMAL(14,2) NOT NULL,payment_mode ENUM('cash','cheque','online') NOT NULL,expense_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,reference_no VARCHAR(100),description VARCHAR(255),created_by BIGINT UNSIGNED,UNIQUE KEY uq_expense_no(location_id,expense_no),FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,FOREIGN KEY(category_id) REFERENCES expense_categories(id) ON DELETE RESTRICT,FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,CHECK(amount>0))ENGINE=InnoDB;
CREATE TABLE audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED,location_id BIGINT UNSIGNED,action VARCHAR(50) NOT NULL,entity_type VARCHAR(50) NOT NULL,entity_id BIGINT UNSIGNED,old_values JSON,new_values JSON,ip_address VARCHAR(45),user_agent VARCHAR(500),created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE SET NULL,KEY idx_audit(entity_type,entity_id,created_at))ENGINE=InnoDB;

INSERT INTO locations(code,name,city) VALUES('MAIN','Main LPG Shop','Lahore');
INSERT INTO roles(code,name,description) VALUES('ADMIN','Administrator','Full system access'),('MANAGER','Manager','Operational access'),('CASHIER','Cashier','POS and cash access');
INSERT INTO permissions(code,name) VALUES('DASHBOARD_VIEW','View dashboard'),('POS_SALE','Create POS sales'),('POS_VOID','Void posted sales'),('CUSTOMER_MANAGE','Manage customers'),('SUPPLIER_MANAGE','Manage suppliers'),('RATE_MANAGE','Manage LPG rates'),('INVENTORY_MANAGE','Manage inventory'),('PURCHASE_MANAGE','Manage purchases'),('CASH_MANAGE','Manage counter cash'),('EXPENSE_MANAGE','Manage expenses'),('REPORT_VIEW','View reports'),('USER_MANAGE','Manage users'),('AUDIT_VIEW','View audit log');
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='ADMIN';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='MANAGER' AND p.code<>'USER_MANAGE';
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r JOIN permissions p ON p.code IN('DASHBOARD_VIEW','POS_SALE','CUSTOMER_MANAGE','REPORT_VIEW') WHERE r.code='CASHIER';
-- Local development account: admin / admin123
INSERT INTO users(location_id,role_id,full_name,username,email,password_hash) SELECT l.id,r.id,'System Administrator','admin','admin@perfectlpg.local','$2y$12$9MTfd/L4bb/9R6o1/DWQB.gjYAQReoFRajJCgiNbych8g3iRfVdWm' FROM locations l JOIN roles r ON r.code='ADMIN' WHERE l.code='MAIN';
INSERT INTO cash_registers(location_id,code,name) SELECT id,'REG-01','Main Counter' FROM locations WHERE code='MAIN';
INSERT INTO expense_categories(code,name) VALUES('BOWSER','Bowser / Transport'),('SALARY','Salary / Wages'),('UTILITIES','Utilities'),('MAINTENANCE','Maintenance'),('OTHER','Other');
INSERT INTO inventory_policies(location_id,cylinder_type_id) SELECT id,NULL FROM locations;
INSERT INTO cylinder_types(code,name,capacity_kg,sort_order) VALUES('C6','6 kg',6,1),('C11_8','11.8 kg',11.8,2),('C15','15 kg',15,3),('C35','35 kg',35,4),('C45','45 kg',45,5),('C45_2','45.2 kg',45.2,6);
