CREATE TABLE IF NOT EXISTS inventory_adjustments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 adjustment_no VARCHAR(40) NULL UNIQUE,
 location_id BIGINT UNSIGNED NOT NULL,
 inventory_type ENUM('gas_kg','filled_cylinder','empty_cylinder') NOT NULL,
 cylinder_type_id BIGINT UNSIGNED NULL,
 adjustment_scope ENUM('bulk','specific') NOT NULL,
 direction ENUM('in','out') NOT NULL,
 quantity DECIMAL(14,3) NOT NULL,
 actual_gas_weight_kg DECIMAL(14,3) NOT NULL DEFAULT 0,
 source_cylinder_unit_id BIGINT UNSIGNED NULL,
 before_state JSON NULL,
 after_state JSON NULL,
 reason VARCHAR(120) NOT NULL,
 notes VARCHAR(500) NULL,
 status ENUM('posted','reversed') NOT NULL DEFAULT 'posted',
 created_by BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE RESTRICT,
 FOREIGN KEY(cylinder_type_id) REFERENCES cylinder_types(id) ON DELETE RESTRICT,
 FOREIGN KEY(source_cylinder_unit_id) REFERENCES cylinder_units(id) ON DELETE SET NULL,
 FOREIGN KEY(created_by) REFERENCES users(id) ON DELETE SET NULL,
 KEY idx_inventory_adjustments_location_date(location_id,created_at),
 KEY idx_inventory_adjustments_type(location_id,inventory_type,cylinder_type_id),
 KEY idx_inventory_adjustments_unit(location_id,source_cylinder_unit_id,created_at)
) ENGINE=InnoDB;