<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Cylinder Types</h4><div class="text-muted small">Edit specifications, activate/deactivate types, or delete a type only when it has no stock and no transaction references.</div></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#form" onclick="resetTypeForm()">Add Type</button></div>
<div class="card"><div class="card-body table-responsive"><table class="table table-sm datatable"><thead><tr><th>Code</th><th>Name</th><th>Capacity KG</th><th>Tare KG</th><th>Empty Sale Price</th><th>Order</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>
<?php foreach($types as $t): ?>
<tr><td><?= esc($t['code']) ?></td><td><?= esc($t['name']) ?></td><td><?= number_format((float)$t['capacity_kg'],3) ?></td><td><?= $t['tare_weight_kg']===null?'—':number_format((float)$t['tare_weight_kg'],3) ?></td><td><?= number_format((float)($t['empty_cylinder_price']??0),2) ?></td><td><?= (int)$t['sort_order'] ?></td><td><span class="badge <?= $t['is_active']?'bg-success':'bg-secondary' ?>"><?= $t['is_active']?'Active':'Inactive' ?></span></td>
<td class="text-end"><button class="btn btn-sm btn-outline-primary" onclick='editType(<?= json_encode($t,JSON_HEX_TAG|JSON_HEX_APOS|JSON_HEX_AMP|JSON_HEX_QUOT) ?>)'>Edit</button>
<form method="post" action="<?=site_url('cylinder-types/toggle')?>" class="d-inline"><?=csrf_field()?><input type="hidden" name="id" value="<?=$t['id']?>"><button class="btn btn-sm btn-outline-secondary"><?= $t['is_active']?'Deactivate':'Activate' ?></button></form>
<form method="post" action="<?=site_url('cylinder-types/delete')?>" class="d-inline" onsubmit="return confirm('Delete this cylinder type? This is allowed only when it has no stock or transaction references.')"><?=csrf_field()?><input type="hidden" name="id" value="<?=$t['id']?>"><button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>
<?php endforeach; ?></tbody></table></div></div>
<div class="modal fade" id="form" tabindex="-1"><div class="modal-dialog"><form method="post" action="<?=site_url('cylinder-types/save')?>" class="modal-content"><?=csrf_field()?><input type="hidden" name="id" id="type_id"><div class="modal-header"><h5 id="formTitle">Add Cylinder Type</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">
<?php foreach([['code','Code'],['name','Name'],['capacity_kg','Capacity KG'],['tare_weight_kg','Tare Weight KG'],['empty_cylinder_price','Empty Sale Price'],['sort_order','Sort Order']] as [$n,$l]): ?><div class="mb-3"><label class="form-label"><?=$l?></label><input id="type_<?=$n?>" name="<?=$n?>" type="<?=str_contains($n,'kg')||$n==='sort_order'?'number':'text'?>" step="0.001" class="form-control" <?=in_array($n,['code','name','capacity_kg','empty_cylinder_price'])?'required':''?>></div><?php endforeach; ?><div class="form-check"><input id="type_is_active" name="is_active" value="1" type="checkbox" class="form-check-input" checked><label class="form-check-label">Active</label></div></div><div class="modal-footer"><button class="btn btn-primary">Save Type</button></div></form></div></div>
<?= $this->section('scripts') ?><script>
function resetTypeForm(){document.getElementById('formTitle').textContent='Add Cylinder Type';document.getElementById('type_id').value='';['code','name','capacity_kg','tare_weight_kg','sort_order'].forEach(n=>document.getElementById('type_'+n).value='');document.getElementById('type_is_active').checked=true;}
function editType(t){document.getElementById('formTitle').textContent='Edit Cylinder Type';document.getElementById('type_id').value=t.id;document.getElementById('type_code').value=t.code||'';document.getElementById('type_name').value=t.name||'';document.getElementById('type_capacity_kg').value=t.capacity_kg||'';document.getElementById('type_tare_weight_kg').value=t.tare_weight_kg??'';document.getElementById('type_empty_cylinder_price').value=t.empty_cylinder_price??0;document.getElementById('type_sort_order').value=t.sort_order||0;document.getElementById('type_is_active').checked=!!Number(t.is_active);bootstrap.Modal.getOrCreateInstance(document.getElementById('form')).show();}
</script><?= $this->endSection() ?>
<?= $this->endSection() ?>