<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Stock Adjustment</h4><div class="text-muted small">Correct physical stock safely. Every adjustment gets a reference number and permanent history.</div></div><a class="btn btn-outline-secondary" href="<?=site_url('inventory')?>"><i class="bi bi-box-seam me-1"></i>Inventory</a></div>
<?php if(session()->getFlashdata('success')):?><div class="alert alert-success"><?=esc(session()->getFlashdata('success'))?></div><?php endif;?>
<?php if(session()->getFlashdata('error')):?><div class="alert alert-danger"><?=esc(session()->getFlashdata('error'))?></div><?php endif;?>
<div class="row g-2 mb-3"><?php foreach($rows as $r):?><div class="col-6 col-md-3 col-xl-2"><div class="card h-100 shadow-sm"><div class="card-body py-2"><div class="small text-muted"><?=esc($r['name'])?></div><div class="fs-5 fw-bold"><?=number_format((float)$r['stock'],3)?><?= $r['type']==='gas_kg'?' KG':''?></div></div></div></div><?php endforeach;?></div>
<div class="card shadow-sm mb-4"><div class="card-header bg-white"><h5 class="mb-0">New Adjustment</h5><div class="small text-muted">Choose only what you need; irrelevant fields are hidden automatically.</div></div><div class="card-body"><form method="post" action="<?=site_url('inventory/adjust')?>" id="adjustmentForm"><?=csrf_field()?><div class="row g-3">
<div class="col-md-4"><label class="form-label fw-semibold">What do you want to adjust?</label><select name="inventory_type" id="adjustType" class="form-select"><option value="gas_kg">Gas (KG)</option><option value="filled_cylinder">Filled Cylinder</option><option value="empty_cylinder">Empty Cylinder</option></select></div>
<div class="col-md-4"><label class="form-label fw-semibold">Adjustment level</label><select name="adjustment_scope" id="adjustScope" class="form-select"><option value="bulk">By Cylinder Type</option><option value="specific">One Physical Cylinder</option></select></div>
<div class="col-md-4"><label class="form-label fw-semibold">Direction</label><div class="d-flex gap-2"><label class="form-check border rounded px-3 py-2 flex-fill"><input class="form-check-input me-1" type="radio" name="direction" value="in" checked> Increase</label><label class="form-check border rounded px-3 py-2 flex-fill"><input class="form-check-input me-1" type="radio" name="direction" value="out"> Decrease</label></div></div>
<div class="col-md-5" id="typeWrap"><label class="form-label fw-semibold">Cylinder Type</label><select name="cylinder_type_id" id="adjustCylinderType" class="form-select"><option value="">Select cylinder type</option><?php foreach($types as $t):?><option value="<?=$t['id']?>"><?=esc($t['code'].' — '.$t['name'].' ('.($t['capacity_kg']??0).' KG)')?></option><?php endforeach;?></select></div>
<div class="col-md-7" id="sourceCylinderWrap"><label class="form-label fw-semibold">Physical Cylinder</label><select name="source_cylinder_unit_id" id="sourceCylinder" class="form-select"><option value="">Select physical cylinder</option><?php foreach($units as $u):?><option value="<?=$u['id']?>" data-type="<?=$u['cylinder_type_id']?>" data-status="<?=$u['status']?>" data-gas="<?=$u['gas_weight_kg']?>" data-capacity="<?=$u['capacity_kg']??0?>"><?=esc($u['unit_code'].' — '.$u['cylinder_code'].' — '.$u['cylinder_name'].' — '.ucfirst($u['status']).' — '.number_format((float)$u['gas_weight_kg'],3).' KG')?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label fw-semibold" id="quantityLabel">Quantity</label><input name="quantity" id="adjustQuantity" class="form-control" type="number" min=".01" step=".01" inputmode="decimal" placeholder="Enter quantity" required></div>
<div class="col-md-4" id="actualGasWrap"><label class="form-label fw-semibold">Gas KG per Filled Cylinder</label><input name="actual_gas_weight_kg" id="adjustActualGas" class="form-control" type="number" min=".001" step=".001" placeholder="Gas KG"></div>
<div class="col-md-4"><label class="form-label fw-semibold">Reason</label><select name="reason" id="adjustReason" class="form-select" required><option value="">Select reason</option><option>Physical stock count correction</option><option>Damaged cylinder</option><option>Lost cylinder</option><option>Found cylinder</option><option>Gas leakage</option><option>Refill correction</option><option>Opening/count correction</option><option>Other</option></select></div>
<div class="col-12"><label class="form-label">Notes</label><input name="notes" id="adjustNotes" class="form-control" maxlength="500" placeholder="Additional details (optional)"></div>
<div class="col-12"><div class="alert alert-light border mb-2" id="stockPreview">Select the cylinder type or physical cylinder to see the current stock and expected change.</div><div class="alert alert-info border mb-3" id="adjustHelp"></div><button class="btn btn-primary"><i class="bi bi-check2-circle me-1"></i>Post Adjustment</button></div>
</div></form></div></div>
<div class="card shadow-sm"><div class="card-header bg-white"><h5 class="mb-0">Adjustment History</h5><div class="small text-muted">Manual stock adjustments only. Each row represents one complete adjustment transaction.</div></div><div class="card-body">
<form method="get" class="row g-2 mb-3"><div class="col-md-2"><label class="small text-muted">From</label><input type="date" name="from_date" class="form-control" value="<?=esc($fromDate)?>"></div><div class="col-md-2"><label class="small text-muted">To</label><input type="date" name="to_date" class="form-control" value="<?=esc($toDate)?>"></div><div class="col-md-2"><label class="small text-muted">Item</label><select name="inventory_type" class="form-select"><option value="">All</option><option value="gas_kg" <?=$filterType==='gas_kg'?'selected':''?>>Gas</option><option value="filled_cylinder" <?=$filterType==='filled_cylinder'?'selected':''?>>Filled Cylinder</option><option value="empty_cylinder" <?=$filterType==='empty_cylinder'?'selected':''?>>Empty Cylinder</option></select></div><div class="col-md-2"><label class="small text-muted">Direction</label><select name="direction" class="form-select"><option value="">All</option><option value="in" <?=$filterDirection==='in'?'selected':''?>>Increase</option><option value="out" <?=$filterDirection==='out'?'selected':''?>>Decrease</option></select></div><div class="col-md-2"><label class="small text-muted">Cylinder Type</label><select name="cylinder_type_id" class="form-select"><option value="">All</option><?php foreach($types as $t):?><option value="<?=$t['id']?>" <?=$filterCylinder==(int)$t['id']?'selected':''?>><?=esc($t['code'])?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="small text-muted">Search</label><input name="q" class="form-control" value="<?=esc($search)?>" placeholder="ADJ / reason / cylinder"></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Apply Filters</button><a class="btn btn-outline-secondary" href="<?=site_url('inventory/adjustments')?>">Clear</a></div></form>
<div class="table-responsive"><table class="table table-sm table-striped align-middle mb-0"><thead><tr><th>Reference</th><th>Date/Time</th><th>Adjustment</th><th>Cylinder</th><th>Physical Unit</th><th>Change</th><th>Before → After</th><th>Reason</th><th>User</th><th></th></tr></thead><tbody>
<?php foreach($history as $h): $item=$h['inventory_type']==='gas_kg'?'Gas':($h['inventory_type']==='filled_cylinder'?'Filled Cylinder':'Empty Cylinder'); $before=$h['before_state'];$after=$h['after_state']; $change=number_format((float)$h['quantity'],3).($h['inventory_type']==='gas_kg'?' KG':''); $beforeText=$h['adjustment_scope']==='specific'?number_format((float)($before['gas_weight_kg']??0),3).' KG':number_format((int)($before['cylinder_count']??0)).' units'; $afterText=$h['adjustment_scope']==='specific'?number_format((float)($after['gas_weight_kg']??0),3).' KG':number_format((int)($after['cylinder_count']??0)).' units'; ?>
<tr><td><strong><?=esc($h['adjustment_no']??'—')?></strong></td><td><?=esc($h['created_at'])?></td><td><?=esc($item)?><div class="small text-muted"><?=esc(ucfirst($h['adjustment_scope']))?></div></td><td><?=esc(($h['cylinder_code']??'').($h['cylinder_name']?' — '.$h['cylinder_name']:''))?></td><td><?=esc($h['source_unit_code']??'—')?></td><td><span class="badge <?=$h['direction']==='out'?'text-bg-danger':'text-bg-success'?>"><?= $h['direction']==='out'?'−':'+' ?> <?=esc($change)?></span></td><td><?=esc($beforeText)?> <span class="text-muted">→</span> <strong><?=esc($afterText)?></strong></td><td><?=esc($h['reason'])?><?php if(!empty($h['notes'])):?><div class="small text-muted"><?=esc($h['notes'])?></div><?php endif;?></td><td><?=esc($h['full_name']??'—')?></td><td><a class="btn btn-sm btn-outline-primary" href="<?=site_url('inventory/adjustments/'.$h['id'])?>">View</a></td></tr>
<?php endforeach;?><?php if(!$history):?><tr><td colspan="10" class="text-center text-muted py-4">No stock adjustments found for the selected filters.</td></tr><?php endif;?></tbody></table></div><div class="small text-muted mt-2">Showing up to 500 adjustments for the current branch.</div></div></div>
<script>
const adjustType=document.getElementById('adjustType'),adjustScope=document.getElementById('adjustScope'),adjustCylinderType=document.getElementById('adjustCylinderType'),sourceCylinder=document.getElementById('sourceCylinder'),sourceCylinderWrap=document.getElementById('sourceCylinderWrap'),quantity=document.getElementById('adjustQuantity'),quantityLabel=document.getElementById('quantityLabel'),actualGas=document.getElementById('adjustActualGas'),actualGasWrap=document.getElementById('actualGasWrap'),preview=document.getElementById('stockPreview'),help=document.getElementById('adjustHelp');
function refreshAdjustment(){const type=adjustType.value,increase=document.querySelector('input[name="direction"]:checked')?.value==='in';if(type==='gas_kg')adjustScope.value='specific';Array.from(adjustScope.options).forEach(o=>o.disabled=type==='gas_kg'&&o.value!=='specific');const specific=adjustScope.value==='specific',filled=type==='filled_cylinder';sourceCylinderWrap.style.display=specific?'block':'none';sourceCylinder.disabled=!specific;sourceCylinder.required=specific;adjustCylinderType.required=true;Array.from(sourceCylinder.options).forEach(o=>{if(!o.value)return;const match=adjustCylinderType.value!==''&&o.dataset.type===adjustCylinderType.value,status=o.dataset.status;let valid=match;if(type==='gas_kg')valid=match&&(status==='filled'||status==='empty');else if(type==='filled_cylinder')valid=match&&(increase?status==='empty':status==='filled');else valid=match&&status==='empty'&&!increase;o.hidden=!valid;if(!valid&&o.selected)sourceCylinder.value='';});quantity.max=specific&&type!=='gas_kg'?'1':'';quantity.step='.01';quantityLabel.textContent=type==='gas_kg'?'Gas Quantity (KG)':'Cylinder Quantity';actualGasWrap.style.display=filled&&increase?'block':'none';actualGas.disabled=!(filled&&increase);actualGas.required=filled&&increase;help.textContent=specific?(type==='gas_kg'?'Gas changes the actual weight on the selected physical cylinder. When gas reaches zero, the cylinder becomes empty.':'Only the selected physical cylinder is changed. Its before/after state is recorded in history.'):(type==='filled_cylinder'&&increase?'Creates new filled physical cylinders with the entered gas weight per cylinder.':'Adjusts physical cylinder quantity by the selected cylinder type.');updatePreview();}
function updatePreview(){const o=sourceCylinder.options[sourceCylinder.selectedIndex],t=adjustCylinderType.options[adjustCylinderType.selectedIndex],type=adjustType.value,specific=adjustScope.value==='specific',dir=document.querySelector('input[name="direction"]:checked')?.value==='in',q=Number(quantity.value||0);if(specific&&o&&o.value){const gas=Number(o.dataset.gas||0),cap=Number(o.dataset.capacity||0);preview.innerHTML='<strong>'+o.text.split(' — ')[0]+'</strong> · Current gas: <strong>'+gas.toFixed(3)+' KG</strong> · Capacity: '+cap.toFixed(3)+' KG<br>Expected: '+(dir?'+':'−')+q.toFixed(3)+(type==='gas_kg'?' KG':' unit(s)');}else if(t&&t.value){preview.innerHTML='<strong>'+t.text+'</strong><br>Current stock will be revalidated when you post the adjustment. Exact before/after values will be recorded in history.';}else preview.textContent='Select the cylinder type or physical cylinder to see the current stock and expected change.';}
[adjustType,adjustScope,adjustCylinderType,sourceCylinder,quantity].forEach(e=>e?.addEventListener('change',refreshAdjustment));quantity?.addEventListener('input',updatePreview);document.querySelectorAll('input[name="direction"]').forEach(e=>e.addEventListener('change',refreshAdjustment));refreshAdjustment();
</script>
<?= $this->endSection() ?>