<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<h4>Inventory Controls & Wastage</h4>
<p class="text-muted">Configure stock validation and permitted wastage, then record cylinder leakage or residual gas when a filled cylinder is made empty.</p>
<?php if(session()->getFlashdata('success')):?><div class="alert alert-success"><?=esc(session()->getFlashdata('success'))?></div><?php endif;?>
<?php if(session()->getFlashdata('error')):?><div class="alert alert-danger"><?=esc(session()->getFlashdata('error'))?></div><?php endif;?>
<div class="card mb-4"><div class="card-body">
<h6>Shop Default Policy</h6><form method="post" action="<?=site_url('inventory/controls/save')?>" class="row g-2"><?=csrf_field()?>
<input type="hidden" name="cylinder_type_id" value="">
<div class="col-md-3"><label class="form-label">Stock validation</label><select name="stock_validation_enabled" class="form-select"><option value="1" <?=!empty($policies['default']['stock_validation_enabled'])?'selected':''?>>ON — block overselling</option><option value="0" <?=empty($policies['default']['stock_validation_enabled'])?'selected':''?>>OFF — allow with confirmation</option></select></div>
<div class="col-md-3"><label class="form-label">Wastage basis</label><select name="wastage_mode" class="form-select"><option value="percent" <?=$policies['default']['wastage_mode']==='percent'?'selected':''?>>Percentage</option><option value="fixed_kg" <?=$policies['default']['wastage_mode']==='fixed_kg'?'selected':''?>>Fixed KG</option></select></div>
<div class="col-md-2"><label class="form-label">Wastage %</label><input name="wastage_percent" class="form-control" type="number" step=".001" min="0" max="100" value="<?=esc($policies['default']['wastage_percent'])?>"></div>
<div class="col-md-2"><label class="form-label">Fixed KG</label><input name="wastage_fixed_kg" class="form-control" type="number" step=".001" min="0" value="<?=esc($policies['default']['wastage_fixed_kg'])?>"></div>
<div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Save Default</button></div>
</form>
<hr><h6>Cylinder-Type Overrides</h6>
<?php foreach($types as $t):$p=$policies[(int)$t['id']];?>
<form method="post" action="<?=site_url('inventory/controls/save')?>" class="row g-2 border-top py-2"><?=csrf_field()?><input type="hidden" name="cylinder_type_id" value="<?=$t['id']?>">
<div class="col-md-2 pt-2"><?=esc($t['code'].' — '.$t['name'])?></div><div class="col-md-2"><select name="stock_validation_enabled" class="form-select"><option value="1" <?=$p['stock_validation_enabled']?'selected':''?>>Validation ON</option><option value="0" <?=!$p['stock_validation_enabled']?'selected':''?>>Validation OFF</option></select></div><div class="col-md-2"><select name="wastage_mode" class="form-select"><option value="percent" <?=$p['wastage_mode']==='percent'?'selected':''?>>Percentage</option><option value="fixed_kg" <?=$p['wastage_mode']==='fixed_kg'?'selected':''?>>Fixed KG</option></select></div><div class="col-md-2"><input name="wastage_percent" class="form-control" type="number" step=".001" min="0" max="100" value="<?=esc($p['wastage_percent'])?>"></div><div class="col-md-2"><input name="wastage_fixed_kg" class="form-control" type="number" step=".001" min="0" value="<?=esc($p['wastage_fixed_kg'])?>"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Save Override</button></div></form>
<?php endforeach;?></div></div>
<div class="card"><div class="card-body"><h6>Record Cylinder Gas Wastage / Leakage</h6><div class="alert alert-info small">Select an available filled cylinder, enter gas lost from that physical cylinder, and provide a reason. The cylinder becomes empty stock and the lost gas is recorded in the wastage report.</div>
<form method="post" action="<?=site_url('inventory/wastage/record')?>" class="row g-2"><?=csrf_field()?><div class="col-md-5"><label class="form-label">Filled cylinder</label><select name="cylinder_unit_id" class="form-select" required><option value="">Select cylinder</option><?php foreach($units as $u):?><option value="<?=$u['id']?>"><?=esc($u['code'].' — '.$u['name'].' — '.$u['unit_code'].' — '.$u['gas_weight_kg'].' kg available')?></option><?php endforeach;?></select></div><div class="col-md-3"><label class="form-label">Gas wasted (KG)</label><input name="gas_weight_kg" class="form-control" type="number" step=".001" min=".001" required></div><div class="col-md-4"><label class="form-label">Reason</label><input name="reason" class="form-control" placeholder="Leakage / residual gas / refill wastage" required></div><div class="col-12"><button class="btn btn-warning">Record Wastage & Make Cylinder Empty</button></div></form>
<hr><h6>Wastage History</h6><form class="row g-2 mb-3"><div class="col-md-3"><input name="from" type="date" class="form-control" value="<?=esc($this->request->getGet('from')??'')?>"></div><div class="col-md-3"><input name="to" type="date" class="form-control" value="<?=esc($this->request->getGet('to')??'')?>"></div><div class="col-md-3"><select name="cylinder_type_id" class="form-select"><option value="">All cylinder types</option><?php foreach($types as $t):?><option value="<?=$t['id']?>" <?=((string)$this->request->getGet('cylinder_type_id')===(string)$t['id'])?'selected':''?>><?=esc($t['code'].' — '.$t['name'])?></option><?php endforeach;?></select></div><div class="col-md-3"><button class="btn btn-outline-secondary">Filter</button></div></form>
<table class="table table-sm datatable"><thead><tr><th>Date</th><th>Cylinder</th><th>Unit</th><th>Wasted KG</th><th>Reason</th><th>User</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=esc($r['created_at'])?></td><td><?=esc(($r['cylinder_code']??'').' — '.($r['cylinder_name']??''))?></td><td><?=esc($r['unit_code']??'')?></td><td><?=number_format((float)$r['gas_weight_kg'],3)?></td><td><?=esc($r['reason'])?></td><td><?=esc($r['full_name']??'')?></td></tr><?php endforeach;?></tbody></table>
</div></div>
<?= $this->endSection() ?>