<?php
namespace App\Controllers;
use App\Services\CashService;
use App\Services\AuditService;
use CodeIgniter\Controller;
use Config\Database;
class Expenses extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('EXPENSE_MANAGE')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();return view('expenses/index',['title'=>'Expenses','categories'=>$db->table('expense_categories')->where('is_active',1)->orderBy('name')->get()->getResultArray(),'expenses'=>$db->table('expenses e')->select('e.*,c.name category_name')->join('expense_categories c','c.id=e.category_id')->where('e.location_id',(int)session()->get('location_id'))->orderBy('e.id','DESC')->limit(50)->get()->getResultArray(),'cash'=>(new CashService())->openSessionForLocation((int)session()->get('location_id'))]);}
 public function save(){if($r=$this->guard())return $r;try{$amount=(float)$this->request->getPost('amount');$mode=(string)$this->request->getPost('payment_mode');if($amount<=0||!in_array($mode,['cash','cheque','online'],true))throw new \RuntimeException('Invalid expense.');$db=Database::connect();$cash=0;if($mode==='cash')$cash=$amount;$db->transBegin();$no='E'.date('YmdHis').'-'.random_int(100,999);$db->table('expenses')->insert(['expense_no'=>$no,'location_id'=>(int)session()->get('location_id'),'category_id'=>(int)$this->request->getPost('category_id'),'amount'=>$amount,'payment_mode'=>$mode,'expense_at'=>date('Y-m-d H:i:s'),'reference_no'=>trim((string)$this->request->getPost('reference_no'))?:null,'description'=>trim((string)$this->request->getPost('description'))?:null,'created_by'=>(int)session()->get('user_id')]);$id=(int)$db->insertID();if($cash){$s=(new CashService())->openSessionForLocation((int)session()->get('location_id'));if(!$s)throw new \RuntimeException('Open the counter cash session before a cash expense.');(new CashService())->postGeneric((int)$s['id'],'expense','out',$cash,'expense',$id,(int)session()->get('user_id'),'Expense cash');}if(!$db->transStatus())throw new \RuntimeException('Expense posting failed.');$db->transCommit();AuditService::log('CREATE','expense',$id,null,['expense_no'=>$no,'amount'=>$amount],(int)session()->get('user_id'),(int)session()->get('location_id'));return redirect()->to('/expenses')->with('success','Expense '.$no.' posted.');}catch(\Throwable $e){if(isset($db)&&$db->transStatus()!==false)$db->transRollback();return redirect()->back()->withInput()->with('error',$e->getMessage());}}
}