<?php
namespace App\Controllers;
use App\Services\InventoryService;
use CodeIgniter\Controller;
use Config\Database;
class Inventory extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('INVENTORY_MANAGE')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();$types=$db->table('cylinder_types')->where('is_active',1)->orderBy('sort_order')->get()->getResultArray();$inv=new InventoryService();$locationId=(int)session()->get('location_id');$rows=[['type'=>'gas_kg','id'=>'','name'=>'Gas (KG)','stock'=>$inv->stock($locationId,'gas_kg')]];foreach($types as $t){$rows[]=['type'=>'filled_cylinder','id'=>$t['id'],'name'=>'Filled '.$t['name'],'stock'=>$inv->stock($locationId,'filled_cylinder',(int)$t['id'])];$rows[]=['type'=>'empty_cylinder','id'=>$t['id'],'name'=>'Empty '.$t['name'],'stock'=>$inv->stock($locationId,'empty_cylinder',(int)$t['id'])];}return view('inventory/index',['title'=>'Inventory','rows'=>$rows,'types'=>$types]);}
 public function adjustments(){if($r=$this->guard())return $r;$db=Database::connect();$locationId=(int)session()->get('location_id');$types=$db->table('cylinder_types')->where('is_active',1)->orderBy('sort_order')->get()->getResultArray();$inv=new InventoryService();$rows=[['type'=>'gas_kg','id'=>'','name'=>'Gas (KG)','stock'=>$inv->stock($locationId,'gas_kg')]];foreach($types as $t){$rows[]=['type'=>'filled_cylinder','id'=>$t['id'],'name'=>'Filled '.$t['name'],'stock'=>$inv->stock($locationId,'filled_cylinder',(int)$t['id'])];$rows[]=['type'=>'empty_cylinder','id'=>$t['id'],'name'=>'Empty '.$t['name'],'stock'=>$inv->stock($locationId,'empty_cylinder',(int)$t['id'])];}$history=$db->table('inventory_movements im')->select("im.*,ct.code cylinder_code,ct.name cylinder_name,u.full_name,s.sale_no,p.purchase_no")->join('cylinder_types ct','ct.id=im.cylinder_type_id','left')->join('users u','u.id=im.created_by','left')->join('sales s','s.id=im.source_id','left')->join('purchases p','p.id=im.source_id','left')->where('im.location_id',$locationId)->orderBy('im.movement_at','DESC')->orderBy('im.id','DESC')->limit(500)->get()->getResultArray();return view('inventory/adjustments',['title'=>'Stock Adjustment & History','rows'=>$rows,'types'=>$types,'history'=>$history]);}
 public function adjust(){if($r=$this->guard())return $r;try{$sourceRaw=$this->request->getPost('source_cylinder_unit_id');$sourceId=$sourceRaw!==null&&$sourceRaw!==''?(int)$sourceRaw:null;(new InventoryService())->adjust((int)session()->get('location_id'),(string)$this->request->getPost('inventory_type'),$this->request->getPost('cylinder_type_id')!==''?(int)$this->request->getPost('cylinder_type_id'):null,(float)$this->request->getPost('quantity'),(string)$this->request->getPost('direction'),(int)session()->get('user_id'),$this->request->getPost('notes'),(float)$this->request->getPost('actual_gas_weight_kg'),$sourceId,(string)($this->request->getPost('adjustment_scope')??'bulk'));return redirect()->to('/inventory/adjustments')->with('success','Inventory adjustment posted.');}catch(\Throwable $e){return redirect()->back()->withInput()->with('error',$e->getMessage());}}