<?php
namespace App\Controllers;
use App\Services\CashService;
use App\Services\AuditService;
use CodeIgniter\Controller;
use Config\Database;
class Receipts extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('POS_SALE')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();$customers=$db->table('customers')->where('is_active',1)->orderBy('name')->get()->getResultArray();$creditRows=$db->table('sales')->select('customer_id,SUM(credit_amount) AS credit')->where('status','posted')->where('customer_id IS NOT NULL',null,false)->groupBy('customer_id')->get()->getResultArray();$paidRows=$db->table('customer_receipts')->select('customer_id,SUM(amount) AS paid')->where('status','posted')->where('customer_id IS NOT NULL',null,false)->groupBy('customer_id')->get()->getResultArray();$creditByCustomer=[];$paidByCustomer=[];foreach($creditRows as $row){$creditByCustomer[(int)$row['customer_id']]=(float)$row['credit'];}foreach($paidRows as $row){$paidByCustomer[(int)$row['customer_id']]=(float)$row['paid'];}$customerBalances=[];foreach($customers as $customer){$id=(int)$customer['id'];$customerBalances[$id]=(float)$customer['opening_balance']+($creditByCustomer[$id]??0)-($paidByCustomer[$id]??0);}return view('receipts/index',['title'=>'Customer Receipts','customers'=>$customers,'customerBalances'=>$customerBalances,'receipts'=>$db->table('customer_receipts cr')->select('cr.*,c.name customer_name')->join('customers c','c.id=cr.customer_id','left')->where('cr.location_id',(int)session()->get('location_id'))->orderBy('cr.id','DESC')->limit(50)->get()->getResultArray()]);}
 public function save(){if($r=$this->guard())return $r;try{$amount=(float)$this->request->getPost('amount');$mode=(string)$this->request->getPost('payment_mode');$customer=(int)$this->request->getPost('customer_id');if($amount<=0||!$customer||!in_array($mode,['cash','cheque','online'],true))throw new \RuntimeException('Invalid receipt.');$db=Database::connect();$db->transBegin();$customerRow=$db->query('SELECT * FROM customers WHERE id=? AND is_active=1 FOR UPDATE',[$customer])->getRowArray();if(!$customerRow)throw new \RuntimeException('Customer is invalid or inactive.');$creditRow=$db->table('sales')->selectSum('credit_amount','credit')->where(['customer_id'=>$customer,'status'=>'posted'])->get()->getRowArray();$paidRow=$db->table('customer_receipts')->selectSum('amount','paid')->where(['customer_id'=>$customer,'status'=>'posted'])->get()->getRowArray();$outstanding=(float)$customerRow['opening_balance']+(float)($creditRow['credit']??0)-(float)($paidRow['paid']??0);$balanceAfter=$outstanding-$amount;$no='R'.date('YmdHis').'-'.random_int(100,999);$db->table('customer_receipts')->insert(['receipt_no'=>$no,'location_id'=>(int)session()->get('location_id'),'customer_id'=>$customer,'status'=>'posted','amount'=>$amount,'payment_mode'=>$mode,'receipt_at'=>date('Y-m-d H:i:s'),'reference_no'=>trim((string)$this->request->getPost('reference_no'))?:null,'notes'=>trim((string)$this->request->getPost('notes'))?:null,'created_by'=>(int)session()->get('user_id')]);$id=(int)$db->insertID();if($mode==='cash'){$s=(new CashService())->openSessionForLocation((int)session()->get('location_id'));if(!$s)throw new \RuntimeException('Open the counter cash session before a cash receipt.');(new CashService())->postGeneric((int)$s['id'],'customer_receipt','in',$amount,'customer_receipt',$id,(int)session()->get('user_id'),'Customer cash receipt');}if(!$db->transStatus())throw new \RuntimeException('Receipt posting failed.');$db->transCommit();AuditService::log('CREATE','customer_receipt',$id,null,['receipt_no'=>$no,'amount'=>$amount],(int)session()->get('user_id'),(int)session()->get('location_id'));return redirect()->to('/receipts')->with('success','Receipt '.$no.' posted. Current OS: Rs. '.number_format($outstanding,2).'; Received: Rs. '.number_format($amount,2).'; Balance after receipt: Rs. '.number_format($balanceAfter,2).'.');}catch(\Throwable $e){if(isset($db)&&$db->transStatus()!==false)$db->transRollback();return redirect()->back()->withInput()->with('error',$e->getMessage());}}
}