<?php
namespace App\Controllers;
use App\Services\CashService;
use App\Services\AuditService;
use CodeIgniter\Controller;
use Config\Database;
class Receipts extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('POS_SALE')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();return view('receipts/index',['title'=>'Customer Receipts','customers'=>$db->table('customers')->where('is_active',1)->orderBy('name')->get()->getResultArray(),'receipts'=>$db->table('customer_receipts')->where('location_id',(int)session()->get('location_id'))->orderBy('id','DESC')->limit(50)->get()->getResultArray()]);}
 public function save(){if($r=$this->guard())return $r;try{$amount=(float)$this->request->getPost('amount');$mode=(string)$this->request->getPost('payment_mode');$customer=(int)$this->request->getPost('customer_id');if($amount<=0||!$customer||!in_array($mode,['cash','cheque','online'],true))throw new \RuntimeException('Invalid receipt.');$db=Database::connect();$db->transBegin();$customerRow=$db->query('SELECT * FROM customers WHERE id=? AND is_active=1 FOR UPDATE',[$customer])->getRowArray();if(!$customerRow)throw new \RuntimeException('Customer is invalid or inactive.');$creditRow=$db->table('sales')->selectSum('credit_amount','credit')->where(['customer_id'=>$customer,'status'=>'posted'])->get()->getRowArray();$paidRow=$db->table('customer_receipts')->selectSum('amount','paid')->where(['customer_id'=>$customer,'status'=>'posted'])->get()->getRowArray();$outstanding=(float)$customerRow['opening_balance']+(float)($creditRow['credit']??0)-(float)($paidRow['paid']??0);if($amount>$outstanding+0.01)throw new \RuntimeException('Receipt cannot exceed the customer outstanding balance of Rs. '.number_format(max(0,$outstanding),2).'.');$no='R'.date('YmdHis').'-'.random_int(100,999);$db->table('customer_receipts')->insert(['receipt_no'=>$no,'location_id'=>(int)session()->get('location_id'),'customer_id'=>$customer,'status'=>'posted','amount'=>$amount,'payment_mode'=>$mode,'receipt_at'=>date('Y-m-d H:i:s'),'reference_no'=>trim((string)$this->request->getPost('reference_no'))?:null,'notes'=>trim((string)$this->request->getPost('notes'))?:null,'created_by'=>(int)session()->get('user_id')]);$id=(int)$db->insertID();if($mode==='cash'){$s=(new CashService())->openSessionForLocation((int)session()->get('location_id'));if(!$s)throw new \RuntimeException('Open the counter cash session before a cash receipt.');(new CashService())->postGeneric((int)$s['id'],'customer_receipt','in',$amount,'customer_receipt',$id,(int)session()->get('user_id'),'Customer cash receipt');}if(!$db->transStatus())throw new \RuntimeException('Receipt posting failed.');$db->transCommit();AuditService::log('CREATE','customer_receipt',$id,null,['receipt_no'=>$no,'amount'=>$amount],(int)session()->get('user_id'),(int)session()->get('location_id'));return redirect()->to('/receipts')->with('success','Receipt '.$no.' posted.');}catch(\Throwable $e){if(isset($db)&&$db->transStatus()!==false)$db->transRollback();return redirect()->back()->withInput()->with('error',$e->getMessage());}}
}