<?php
namespace App\Controllers;
use CodeIgniter\Controller;
use Config\Database;
class Reports extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('REPORT_VIEW')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();$loc=(int)session()->get('location_id');$today=date('Y-m-d');$sales=$db->table('sales')->select('COUNT(*) count,SUM(total_amount) total,SUM(credit_amount) credit')->where(['location_id'=>$loc,'status'=>'posted'])->where('transaction_type !=','security_deposit')->where('transaction_type !=','cylinder_return')->where('DATE(transaction_at)',$today)->get()->getRowArray();$p=$db->table('purchases')->select('COUNT(*) count,SUM(total_amount) total,SUM(credit_amount) credit')->where(['location_id'=>$loc,'status'=>'posted'])->where('DATE(transaction_at)',$today)->get()->getRowArray();$payments=$db->table('sale_payments sp')->select('payment_mode,SUM(amount) amount')->join('sales s','s.id=sp.sale_id')->where('s.location_id',$loc)->where('s.status','posted')->whereNotIn('s.transaction_type',['security_deposit','cylinder_return'])->where('DATE(sp.payment_at)',$today)->groupBy('payment_mode')->get()->getResultArray();$deposits=$db->table('customer_security_deposits')->select("SUM(CASE WHEN entry_type='hold' THEN amount ELSE 0 END) held,SUM(CASE WHEN entry_type='refund' THEN amount ELSE 0 END) refunded")->where(['location_id'=>$loc])->where('DATE(transaction_at)',$today)->get()->getRowArray();$depositBalance=$db->table('customer_security_deposits')->select("SUM(CASE WHEN entry_type='hold' THEN amount ELSE -amount END) balance")->where(['location_id'=>$loc])->get()->getRowArray();return view('reports/index',['title'=>'Reports','sales'=>$sales,'purchases'=>$p,'payments'=>$payments,'today'=>$today,'deposits'=>$deposits,'depositBalance'=>(float)($depositBalance['balance']??0)]);}
 public function custody(){if($r=$this->guard())return $r;$db=Database::connect();$loc=(int)session()->get('location_id');$rows=$db->table('cylinder_custody cc')->select('cc.*,c.code customer_code,c.name customer_name,cu.unit_code,cu.gas_weight_kg,ct.code cylinder_code,ct.name cylinder_name')->join('customers c','c.id=cc.customer_id')->join('cylinder_units cu','cu.id=cc.cylinder_unit_id')->join('cylinder_types ct','ct.id=cu.cylinder_type_id')->where(['cc.location_id'=>$loc,'cc.status'=>'issued'])->orderBy('c.name')->orderBy('cu.unit_code')->get()->getResultArray();$totals=$db->table('customer_security_deposits')->select("SUM(CASE WHEN entry_type='hold' THEN amount ELSE -amount END) balance")->where(['location_id'=>$loc])->get()->getRowArray();return view('reports/custody',['title'=>'Cylinder Custody & Security Deposits','rows'=>$rows,'depositBalance'=>(float)($totals['balance']??0)]);}
 public function stock(){if($r=$this->guard())return $r;return redirect()->to('/inventory');}
 public function ledger(int $customerId){if($r=$this->guard())return $r;$db=Database::connect();$c=$db->table('customers')->where('id',$customerId)->get()->getRowArray();if(!$c)return $this->response->setStatusCode(404)->setBody('Customer not found');$sales=$db->table('sales')->where(['customer_id'=>$customerId,'status'=>'posted'])->orderBy('transaction_at')->get()->getResultArray();$receipts=$db->table('customer_receipts')->where(['customer_id'=>$customerId,'status'=>'posted'])->orderBy('receipt_at')->get()->getResultArray();return view('reports/ledger',['title'=>'Customer Ledger','customer'=>$c,'sales'=>$sales,'receipts'=>$receipts]);}
}