<?php
namespace App\Controllers;
use App\Services\CashService;
use App\Services\AuditService;
use CodeIgniter\Controller;
use Config\Database;
class SupplierPayments extends Controller{
 private function guard(){return \App\Services\PermissionService::allows('PURCHASE_MANAGE')?null:$this->response->setStatusCode(403)->setBody('Forbidden');}
 public function index(){if($r=$this->guard())return $r;$db=Database::connect();return view('supplier_payments/index',['title'=>'Supplier Payments','suppliers'=>$db->table('suppliers')->where('is_active',1)->orderBy('name')->get()->getResultArray()]);}
 public function save(){if($r=$this->guard())return $r;try{$supplier=(int)$this->request->getPost('supplier_id');$amount=(float)$this->request->getPost('amount');$mode=(string)$this->request->getPost('payment_mode');if(!$supplier||$amount<=0||!in_array($mode,['cash','cheque','online'],true))throw new \RuntimeException('Invalid supplier payment.');$db=Database::connect();$db->transBegin();$supplierRow=$db->query('SELECT * FROM suppliers WHERE id=? AND is_active=1 FOR UPDATE',[$supplier])->getRowArray();if(!$supplierRow)throw new \RuntimeException('Supplier is invalid or inactive.');$locationId=(int)session()->get('location_id');
$creditRow=$db->table('purchases')->selectSum('credit_amount','credit')->where(['supplier_id'=>$supplier,'status'=>'posted','location_id'=>$locationId])->get()->getRowArray();$paidRow=$db->table('supplier_payments')->selectSum('amount','paid')->where(['supplier_id'=>$supplier,'status'=>'posted','location_id'=>$locationId])->get()->getRowArray();$outstanding=(float)$supplierRow['opening_balance']+(float)($creditRow['credit']??0)-(float)($paidRow['paid']??0);if($amount>$outstanding+0.01)throw new \RuntimeException('Supplier payment cannot exceed the outstanding balance of Rs. '.number_format(max(0,$outstanding),2).'.');$no='SP'.date('YmdHis').'-'.random_int(100,999);$db->table('supplier_payments')->insert(['payment_no'=>$no,'location_id'=>(int)session()->get('location_id'),'supplier_id'=>$supplier,'status'=>'posted','amount'=>$amount,'payment_mode'=>$mode,'payment_at'=>date('Y-m-d H:i:s'),'reference_no'=>trim((string)$this->request->getPost('reference_no'))?:null,'notes'=>trim((string)$this->request->getPost('notes'))?:null,'created_by'=>(int)session()->get('user_id')]);$id=(int)$db->insertID();if($mode==='cash'){$s=(new CashService())->openSessionForLocation((int)session()->get('location_id'));if(!$s)throw new \RuntimeException('Open the counter cash session before a cash supplier payment.');(new CashService())->postGeneric((int)$s['id'],'supplier_payment','out',$amount,'supplier_payment',$id,(int)session()->get('user_id'),'Supplier cash payment');}if(!$db->transStatus())throw new \RuntimeException('Supplier payment failed.');$db->transCommit();AuditService::log('CREATE','supplier_payment',$id,null,['payment_no'=>$no,'amount'=>$amount],(int)session()->get('user_id'),(int)session()->get('location_id'));return redirect()->to('/supplier-payments')->with('success','Supplier payment '.$no.' posted.');}catch(\Throwable $e){if(isset($db)&&$db->transStatus()!==false)$db->transRollback();return redirect()->back()->withInput()->with('error',$e->getMessage());}}
}