<?= $this->extend('layouts/app') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-3"><h4>POS Sales</h4><span class="badge text-bg-secondary">Phase 3</span></div>
<?php if(session()->getFlashdata('success')): ?><div class="alert alert-success"><?= esc(session()->getFlashdata('success')) ?></div><?php endif; ?>
<?php if(session()->getFlashdata('error')): ?><div class="alert alert-danger"><?= esc(session()->getFlashdata('error')) ?></div><?php endif; ?>
<form method="post" action="<?= site_url('sales/save') ?>" id="saleForm"><?= csrf_field() ?>
<input type="hidden" name="lines_json" id="lines_json"><input type="hidden" name="payments_json" id="payments_json">
<div class="row g-3">
<div class="col-lg-8"><div class="card"><div class="card-body">
<div class="row g-2 mb-3"><div class="col-md-6"><label class="form-label">Customer</label><select name="customer_id" id="customer_id" class="form-select"><option value="">Walk-in / Cash</option><?php foreach($customers as $c): ?><option value="<?= $c['id'] ?>"><?= esc(($c['code']?$c['code'].' — ':'').$c['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Transaction Time</label><input name="transaction_at" type="datetime-local" class="form-control" value="<?= date('Y-m-dTH:i') ?>"></div></div>
<div class="table-responsive"><table class="table table-sm" id="lines"><thead><tr><th>Type</th><th>Cylinder</th><th>Qty / KG</th><th>Rate</th><th>Total</th><th></th></tr></thead><tbody></tbody></table></div>
<button type="button" class="btn btn-outline-primary" id="addLine">Add Line</button>
</div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-body"><label class="form-label">Discount</label><input name="discount_amount" id="discount" type="number" min="0" step="0.01" value="0" class="form-control mb-3"><div class="mb-3"><strong>Total: Rs. <span id="total">0.00</span></strong></div><div id="payments"></div><button type="button" class="btn btn-outline-secondary mb-3" id="addPayment">Add Payment</button><textarea name="notes" class="form-control mb-3" placeholder="Notes"></textarea><button class="btn btn-primary w-100" id="saveBtn">Post Sale</button></div></div></div>
</div></form>
<script>
const types=<?= json_encode(array_values($types)) ?>;
const rates=<?= json_encode($cylinderRates) ?>;
const kgRate=<?= json_encode($kgRate) ?>;
const tbody=document.querySelector('#lines tbody'), payments=document.getElementById('payments');
function options(){return '<option value="">Select</option>'+types.map(t=>'<option value="'+t.id+'">'+t.code+' — '+t.name+'</option>').join('');}
function addLine(){const tr=document.createElement('tr');tr.innerHTML='<td><select class="form-select kind"><option value="filled_cylinder">Filled cylinder</option><option value="refill_kg">Refill KG</option><option value="cylinder_exchange">Cylinder exchange</option><option value="empty_intake">Empty intake</option><option value="empty_sale">Empty sale</option></select></td><td><select class="form-select cyl">'+options()+'</select></td><td><input class="form-control qty" type="number" min="0.001" step="0.001" value="1"></td><td><input class="form-control rate" type="number" min="0" step="0.0001"></td><td class="lineTotal">0.00</td><td><button type="button" class="btn btn-sm btn-outline-danger remove">×</button></td>';tbody.appendChild(tr);bindLine(tr);}
function bindLine(tr){const kind=tr.querySelector('.kind'),cyl=tr.querySelector('.cyl'),qty=tr.querySelector('.qty'),rate=tr.querySelector('.rate');function sync(){const t=types.find(x=>x.id==cyl.value);const r=kind.value==='refill_kg'?kgRate:(rates[cyl.value]??0);if(document.activeElement!==rate)rate.value=r??'';tr.querySelector('.lineTotal').textContent=(Number(qty.value||0)*Number(rate.value||0)).toFixed(2);calc();}kind.onchange=sync;cyl.onchange=sync;qty.oninput=sync;rate.oninput=sync;tr.querySelector('.remove').onclick=()=>{tr.remove();calc();};sync();}
function calc(){let total=0;tbody.querySelectorAll('tr').forEach(tr=>total+=Number(tr.querySelector('.lineTotal').textContent||0));total-=Number(document.getElementById('discount').value||0);document.getElementById('total').textContent=Math.max(0,total).toFixed(2);}
function addPayment(){const div=document.createElement('div');div.className='input-group mb-2 payment';div.innerHTML='<select class="form-select mode"><option value="cash">Cash</option><option value="cheque">Cheque</option><option value="online">Online</option><option value="credit">Credit</option></select><input class="form-control amount" type="number" min="0.01" step="0.01" placeholder="Amount"><input class="form-control ref" placeholder="Ref"><button type="button" class="btn btn-outline-danger remove">×</button>';payments.appendChild(div);div.querySelector('.remove').onclick=()=>div.remove();}
document.getElementById('addLine').onclick=addLine;document.getElementById('addPayment').onclick=addPayment;document.getElementById('discount').oninput=calc;
document.getElementById('saleForm').onsubmit=()=>{const lines=[...tbody.querySelectorAll('tr')].map(tr=>({line_type:tr.querySelector('.kind').value,cylinder_type_id:tr.querySelector('.cyl').value,quantity:tr.querySelector('.qty').value,gas_weight_kg:tr.querySelector('.kind').value==='refill_kg'?tr.querySelector('.qty').value:undefined,rate:tr.querySelector('.rate').value}));const pays=[...payments.querySelectorAll('.payment')].map(p=>({payment_mode:p.querySelector('.mode').value,amount:p.querySelector('.amount').value,reference_no:p.querySelector('.ref').value}));document.getElementById('lines_json').value=JSON.stringify(lines);document.getElementById('payments_json').value=JSON.stringify(pays);return lines.length>0&&pays.length>0;};
addLine();addPayment();
</script>
<?= $this->endSection() ?>