<?= $this->extend('layouts/app') ?><?= $this->section('content') ?>
<h4>Sales & Daily Reports <small class="text-muted"><?=$from?> to <?=$to?></small></h4><form method="get" class="row g-2 align-items-end mb-3"><div class="col-md-3"><label class="form-label">From Date</label><input type="date" name="from" class="form-control" value="<?=esc($from)?>"></div><div class="col-md-3"><label class="form-label">To Date</label><input type="date" name="to" class="form-control" value="<?=esc($to)?>"></div><div class="col-md-2"><button class="btn btn-primary w-100">Run Report</button></div><div class="col-md-2"><a class="btn btn-outline-secondary w-100" href="<?=site_url('reports')?>">Today</a></div></form>
<div class="row g-3">
<div class="col-md-3"><div class="card card-body"><div class="text-muted">Sales</div><h3>Rs. <?=number_format((float)($sales['total']??0),2)?></h3><div><?=$sales['count']??0?> posted transactions</div><div>Credit Rs. <?=number_format((float)($sales['credit']??0),2)?></div></div></div>
<div class="col-md-3"><div class="card card-body"><div class="text-muted">Purchases</div><h3>Rs. <?=number_format((float)($purchases['total']??0),2)?></h3><div><?=$purchases['count']??0?> posted transactions</div><div>Credit Rs. <?=number_format((float)($purchases['credit']??0),2)?></div></div></div>
<div class="col-md-3"><div class="card card-body"><div class="text-muted">Sales by Payment Mode</div><?php foreach($payments as $p):?><div class="d-flex justify-content-between"><span><?=esc($p['payment_mode'])?></span><strong>Rs. <?=number_format($p['amount'],2)?></strong></div><?php endforeach;?></div></div>
<div class="col-md-3"><div class="card card-body border-warning"><div class="text-muted">Security Deposits Held</div><h3>Rs. <?=number_format((float)$depositBalance,2)?></h3><div>Today received: Rs. <?=number_format((float)($deposits['held']??0),2)?></div><div>Today refunded: Rs. <?=number_format((float)($deposits['refunded']??0),2)?></div><div class="small text-muted mt-1">Refundable liability — not revenue</div></div></div>
</div>
<div class="card mt-3"><div class="card-body"><h5 class="mb-3">Sales Detail</h5><div class="table-responsive"><table class="table table-sm table-hover align-middle mb-0"><thead><tr><th>Sale No.</th><th>Date / Time</th><th>Customer</th><th>Type</th><th class="text-end">Net Amount</th><th class="text-end">Received</th><th class="text-end">Credit / OS</th><th>User</th></tr></thead><tbody><?php if(empty($saleRows)): ?><tr><td colspan="8" class="text-center text-muted py-4">No posted sales found for this period.</td></tr><?php else: foreach($saleRows as $s): $received=max(0,(float)$s['total_amount']-(float)$s['credit_amount']); ?><tr><td class="fw-semibold"><?=esc($s['sale_no'])?></td><td><?=esc($s['transaction_at'])?></td><td><?=esc($s['customer_name']??'Walk-in / Cash')?></td><td><?=esc($s['transaction_type'])?></td><td class="text-end">Rs. <?=number_format((float)$s['total_amount'],2)?></td><td class="text-end">Rs. <?=number_format($received,2)?></td><td class="text-end">Rs. <?=number_format((float)$s['credit_amount'],2)?></td><td><?=esc($s['created_by_name']??'-')?></td></tr><?php endforeach; endif; ?></tbody></table></div></div></div><div class="mt-3 d-flex gap-2><a class="btn btn-outline-primary" href="<?=site_url('inventory')?>">Daily Stock</a><a class="btn btn-outline-success" href="<?=site_url('reports/inventory-detail')?>">Inventory Detail Report</a><a class="btn btn-outline-warning" href="<?=site_url('reports/custody')?>">Cylinder Custody & Deposits</a></div>
<?= $this->endSection() ?>